"""The distinction family (Evgeny, 2026-09-07 13:34): the engines load with their vocabularies, every row is document-scope, the
recipes carry the two rounds, and enumerated fields pin to their vocabularies at parse time."""
import yaml

from src.engines.schemas_v2 import CapabilityEngineDefinition
from src.operationalizations.registry import get_operationalization_registry


def test_the_three_engines_load_with_their_vocabularies_and_the_recipes():
    from src.vocabularies.registry import get_vocabulary_registry
    from src.dossier.catalog import load_recipes
    reg = get_operationalization_registry(); vr = get_vocabulary_registry()
    dims = {}
    for k in ("interlocutor_position", "distinction_draft", "distinction_settle"):
        CapabilityEngineDefinition.model_validate(yaml.safe_load(open(f"src/engines/capability_definitions/{k}.yaml")))
        op = reg.get(k); assert op is not None
        dims[k] = [d.key for d in op.process.dimensions]
        assert all(d.scope == "document" for d in op.process.dimensions) and all(d.id_prefix for d in op.process.dimensions)
    assert dims == {"interlocutor_position": ["question", "their_claim", "their_silence"], "distinction_draft": ["your_position", "relation", "question_back"], "distinction_settle": ["distinction", "effect", "open"]}
    assert vr.values_for("distinction_draft", "relation") == ["parallel", "collides", "overlaps_then_diverges", "absorbs", "irrelevant"]
    assert vr.values_for("distinction_settle", "relation_kind") == ["parallel", "collides", "overlaps_then_diverges", "absorbs", "irrelevant"]
    assert vr.values_for("distinction_settle", "relation") == ["moves", "supports", "complicates", "contradicts"] and vr.get("argument_effects").owner == "the-stacks"
    assert vr.values_for("distinction_draft", "kind") == ["confirm", "restate", "elaborate", "choose"] and vr.values_for("interlocutor_position", "role") == ["foil", "encounter", "ally", "source"]
    recipes = {r["key"]: r for r in load_recipes()}
    assert [s["engine_key"] for s in recipes["distinction_round"]["steps"]] == ["interlocutor_position", "distinction_draft"]
    assert [s["engine_key"] for s in recipes["distinction_settle"]["steps"]] == ["distinction_settle"]


def test_the_relation_and_the_effect_pin_to_their_vocabularies():
    from src.dossier.explainer import rows_with_fields
    out = ("[D2.F1] His position vs Brenner: collides on the state's logic — dim: relation — interlocutor: Brenner — question: I1.F1 — position: D1.F1 — claim: I2.F1 — relation: Collides — axis: the state's own logic — ours: states have imperatives of their own — theirs: the state responds to capital — bridge: none — anchor: \"the state is just a way to respond to capital\" — doc: turn — confidence: high\n"
           "[D2.F2] His position vs Arrighi: overlaps then diverges — dim: relation — interlocutor: Arrighi — question: I1.F1 — position: D1.F1 — claim: I2.F2 — relation: overlaps, then diverges — axis: where the territorial logic comes from — ours: x — theirs: y — bridge: z — anchor: \"the territorial logic is generated by the system\" — doc: turn — confidence: medium")
    rows = rows_with_fields(out, engine_key="distinction_draft")
    assert rows[0]["fields"]["relation"] == "collides" and "drift" not in rows[0]
    assert rows[1]["fields"]["relation"] == "overlaps, then diverges" and rows[1]["drift"][0]["fixed"] is None      # not one vocabulary word: left, reported
    s = "[S2.F1] Part 6 moves: the parity claim shifts to class analysis — dim: effect — distinction: S1.F1 — part: 6 — relation: moves — anchor: \"x\" — doc: answer — confidence: high"
    assert rows_with_fields(s, engine_key="distinction_settle")[0]["fields"]["relation"] == "moves"
