"""The distinction family (Evgeny, 2026-09-07 13:34): the engines load with their vocabularies, every row is document-scope, the
recipes carry the two rounds, and enumerated fields pin to their vocabularies at parse time."""
import yaml

from src.engines.schemas_v2 import CapabilityEngineDefinition
from src.operationalizations.registry import get_operationalization_registry


def test_the_three_engines_load_with_their_vocabularies_and_the_recipes():
    from src.vocabularies.registry import get_vocabulary_registry
    from src.dossier.catalog import load_recipes
    reg = get_operationalization_registry(); vr = get_vocabulary_registry()
    dims = {}
    for k in ("interlocutor_position", "distinction_draft", "distinction_settle"):
        CapabilityEngineDefinition.model_validate(yaml.safe_load(open(f"src/engines/capability_definitions/{k}.yaml")))
        op = reg.get(k); assert op is not None
        dims[k] = [d.key for d in op.process.dimensions]
        assert all(d.scope == "document" for d in op.process.dimensions) and all(d.id_prefix for d in op.process.dimensions)
    assert dims == {"interlocutor_position": ["question", "their_claim", "their_silence"], "distinction_draft": ["your_position", "relation", "question_back"], "distinction_settle": ["distinction", "effect", "open"]}
    assert vr.values_for("distinction_draft", "relation") == ["parallel", "collides", "overlaps_then_diverges", "absorbs", "irrelevant"]
    assert vr.values_for("distinction_settle", "relation_kind") == ["parallel", "collides", "overlaps_then_diverges", "absorbs", "irrelevant"]
    assert vr.values_for("distinction_settle", "relation") == ["moves", "supports", "complicates", "contradicts"] and vr.get("argument_effects").owner == "the-stacks"
    assert vr.values_for("distinction_draft", "kind") == ["confirm", "restate", "elaborate", "choose"] and vr.values_for("interlocutor_position", "role") == ["foil", "encounter", "ally", "source"]
    recipes = {r["key"]: r for r in load_recipes()}
    assert [s["engine_key"] for s in recipes["distinction_round"]["steps"]] == ["interlocutor_position", "distinction_draft"]
    assert [s["engine_key"] for s in recipes["distinction_settle"]["steps"]] == ["distinction_settle"]


def test_the_relation_and_the_effect_pin_to_their_vocabularies():
    from src.dossier.explainer import rows_with_fields
    out = ("[D2.F1] His position vs Brenner: collides on the state's logic — dim: relation — interlocutor: Brenner — question: I1.F1 — position: D1.F1 — claim: I2.F1 — relation: Collides — axis: the state's own logic — ours: states have imperatives of their own — theirs: the state responds to capital — bridge: none — anchor: \"the state is just a way to respond to capital\" — doc: turn — confidence: high\n"
           "[D2.F2] His position vs Arrighi: overlaps then diverges — dim: relation — interlocutor: Arrighi — question: I1.F1 — position: D1.F1 — claim: I2.F2 — relation: overlaps, then diverges — axis: where the territorial logic comes from — ours: x — theirs: y — bridge: z — anchor: \"the territorial logic is generated by the system\" — doc: turn — confidence: medium")
    rows = rows_with_fields(out, engine_key="distinction_draft")
    assert rows[0]["fields"]["relation"] == "collides" and "drift" not in rows[0]
    assert rows[1]["fields"]["relation"] == "overlaps, then diverges" and rows[1]["drift"][0]["fixed"] is None      # not one vocabulary word: left, reported
    s = "[S2.F1] Part 6 moves: the parity claim shifts to class analysis — dim: effect — distinction: S1.F1 — part: 6 — relation: moves — anchor: \"x\" — doc: answer — confidence: high"
    assert rows_with_fields(s, engine_key="distinction_settle")[0]["fields"]["relation"] == "moves"


def test_the_round_renders_by_code_into_interlocutors_and_distinction_challenges():
    from src.dossier.distinctions import render_distinctions
    turn = "focal:turn-11"
    ip = ("[I1.F1] What is the state's counterpart to market dependence: the imperative it cannot escape? — dim: question — interlocutors: Brenner; Hintze; Arrighi — anchor: \"what we need to understand is the way in which one can deduce a logic from the activities of the states\" — doc: focal:turn-11 — confidence: high\n"
          "[I2.F1] Brenner: the state responds to capital, domestically and to the markets internationally — dim: their_claim — interlocutor: Brenner — question: I1.F1 — role: foil — locus: pp. 88–90 — turn_says: no autonomy of any kind — anchor: \"the state is just a way to respond to capital\" — doc: em:BJ4R4EPJ — confidence: high\n"
          "[I2.F2] Arrighi: the territorial logic is a strategy of rulers within the system, not the state's own — dim: their_claim — interlocutor: Arrighi — question: I1.F1 — role: encounter — locus: ch. 1 — turn_says: none — anchor: \"territorialist and capitalist logics are rival strategies of rulers\" — doc: em:ARR2005 — confidence: medium\n"
          "[I3.F1] Hintze does not address market dependence in the held windows — dim: their_silence — interlocutor: Hintze — question: I1.F1 — anchor: \"maybe a solution would lie in Otto Hintze\" — doc: focal:turn-11 — confidence: medium")
    dd = ("[D1.F1] States have imperatives of their own — territorial coherence, security, a developmentalist vision — that can be classified like classes — dim: your_position — question: I1.F1 — part: 6 — anchor: \"we cannot start classifying states into different kinds\" — doc: focal:turn-11 — confidence: medium\n"
          "[D2.F1] Ours vs Brenner: collides on whether the state has a logic of its own — dim: relation — interlocutor: Brenner — question: I1.F1 — position: D1.F1 — claim: I2.F1 — relation: collides — axis: the state's own logic — ours: imperatives of its own — theirs: a response to capital — bridge: none unless impurity is defined — bears_on: 1; 8 — anchor: \"there is no autonomy of any kind\" — doc: focal:turn-11 — confidence: high\n"
          "[D2.F2] Ours vs Arrighi: Overlaps then diverges on where the territorial logic comes from — dim: relation — interlocutor: Arrighi — question: I1.F1 — position: D1.F1 — claim: I2.F2 — relation: overlaps_then_diverges — axis: the system or the state — ours: the state's structural interests — theirs: the system generates it — bridge: a typology of states within the system — anchor: \"generated by the system\" — doc: focal:turn-11 — confidence: medium\n"
          "[D3.F1] Is the state's counterpart to market dependence a set of imperatives (security, reproduction of its capitalist class, territorial coherence), or one of them ranked first? — dim: question_back — from: D2.F1 — interlocutor: Brenner — kind: choose — options: a set | one ranked first | none — anchor: \"some imperatives that have to do with territorial coherence\" — doc: focal:turn-11 — confidence: high")
    job = {"id": "d-dist", "status": "done", "analysis": {"4.1": {"engine_key": "interlocutor_position", "final_output": ip, "final_wall": {"failed_ids": []}},
                                                           "4.2": {"engine_key": "distinction_draft", "final_output": dd, "final_wall": {"failed_ids": ["D2.F2"]}}}}
    out = render_distinctions(job)
    assert out["phases"] == ["interlocutor_position", "distinction_draft"] and out["rows"] == 8 and out["conjectures"] == 1
    assert [i["name"] for i in out["interlocutors"]] == ["Arrighi", "Brenner", "Hintze"]
    assert out["interlocutors"][2]["silences"][0]["question"] == "I1.F1" and out["interlocutors"][1]["claims"][0]["locus"] == "pp. 88–90"
    ch = out["challenges"]; assert len(ch) == 1
    c = ch[0]
    assert c["kind"] == "distinction" and c["interlocutor"] == "Brenner" and c["their_claim"]["doc"] == "em:BJ4R4EPJ" and c["their_claim"]["anchor"].startswith("the state is just")
    assert c["your_position"]["part"] == "6" and c["relation"]["relation"] == "collides" and c["relation"]["axis"] == "the state's own logic"
    assert c["ask"]["kind"] == "choose" and c["ask"]["options"] == ["a set", "one ranked first"] and c["conjecture"] is False
    assert c["bears_on"] == [1, 6, 8]                                                    # the reach: the parts the claim touches plus the part his position sits on
    assert out["vocabulary_drift"] == [] and out["settled"] == [] and out["effects"] == []
    assert render_distinctions({"analysis": {}}) is None


def test_an_added_step_carries_the_recipes_earlier_rows():
    from src.dossier.steps import upstream_findings
    job = {"analysis": {"4.1": {"engine_key": "interlocutor_position", "final_output": "[I1.F1] q — dim: question"}, "4.2": {"engine_key": "oeuvre_trajectory", "final_output": "x"}}}
    assert upstream_findings(job, "distinction_draft") == {"interlocutor_position": "[I1.F1] q — dim: question"}
    assert upstream_findings(job, "interlocutor_position") == {}
    job["analysis"]["4.4"] = {"engine_key": "interlocutor_position", "final_output": "[I1.F1] q2 — dim: question"}     # a re-run supersedes the first
    assert upstream_findings(job, "distinction_draft") == {"interlocutor_position": "[I1.F1] q2 — dim: question"}
    job["analysis"]["4.3"] = {"engine_key": "distinction_draft", "final_output": "[D2.F1] r — dim: relation"}
    assert set(upstream_findings(job, "distinction_settle")) == {"interlocutor_position", "distinction_draft"}   # the recipe's `context`


def test_an_added_step_reads_a_statements_job_and_takes_the_callers_argument_document():
    """The pilot on turn 11 runs over the Stacks' re-read job (one statements document) with the argument's parts sent beside it."""
    from src.dossier.steps import add_step
    texts = {"s1": "{\"statements\": [], \"sources\": []}"}
    job = {"documents": [{"key": "statements", "role": "statements", "executor_doc_id": "s1"}], "analysis": {}, "totals": {}}
    seen = {}
    def fake_call(engine_key, sources, *, packet=None, depth="surface", model=None, spend_cap_usd=2.0, max_chars=None):
        seen.update(keys=[(s.key, s.role) for s in sources], packet=packet, max_chars=max_chars)
        return {"final_output": "[I1.F1] q — dim: question — interlocutors: Brenner — anchor: \"x\" — doc: statements — confidence: high", "wall": {"failed_ids": []}, "cost_usd": 0.1, "calls": [1]}
    add_step(job, "interlocutor_position", get_text=texts.get, call=fake_call, packet_override={"interlocutors": [{"name": "Brenner", "role": "foil"}]},
             extra_sources=[{"key": "argument", "title": "Brief 1, the parts", "text": "[part 1] (his) Market dependence alone does not explain why capitalism grows."}])
    assert seen["keys"] == [("statements", "statements"), ("argument", "source")] and seen["packet"]["interlocutors"][0]["name"] == "Brenner"
    assert job["analysis"]["4.1"]["extra_sources"] == ["argument"] and job["analysis"]["4.1"]["engine_key"] == "interlocutor_position"
    assert seen["max_chars"] == 1_500_000 and job["analysis"]["4.1"]["skipped"] == []
    # the second step carries the first's rows
    add_step(job, "distinction_draft", get_text=texts.get, call=fake_call, extra_sources=[{"key": "argument", "text": "[part 1] (his) …"}])
    assert "interlocutor_position" in seen["packet"]["upstream_findings"] and "4.2" in job["analysis"]


def test_the_distinction_engines_unpack_a_statements_source_and_keep_the_argument_document():
    """The pilot's third run 404ed: the family's per-engine scope table had no entry for the new engines; and the argument document
    carries its own SOURCE ROLE, which the scope filter must let through."""
    import json
    from src.sources.citation_evidence import prepare_citation_sources, FAMILY
    assert {"interlocutor_position", "distinction_draft", "distinction_settle"} <= FAMILY
    statements = json.dumps({"memo": {"uid": "turn-11", "title": "his answer", "markdown": "This is a very good challenge."},
                             "statements": [{"no": 1, "section": "state", "statement": "Brenner argues the state just responds to capital", "sources": ["B1"]}],
                             "sources": [{"label": "B1", "uid": "em:B1", "title": "What Is, and What Is Not, Imperialism?", "text": "The state responds to the interests of capital, domestically and internationally."}]})
    docs = {"statements-exchange-11": statements, "argument": "SOURCE ROLE: argument\n\n[part 6] (his) states have a logic of their own."}
    for engine in ("interlocutor_position", "distinction_draft", "distinction_settle"):
        witnesses, context = prepare_citation_sources(engine, docs)
        assert "argument" in witnesses and any("responds to the interests of capital" in v for v in witnesses.values()), engine
        assert any("This is a very good challenge" in v for v in witnesses.values()) and "statements-exchange-11" not in witnesses


def test_the_impact_scan_loads_and_renders_into_the_distinctions_output():
    from src.operationalizations.registry import get_operationalization_registry
    from src.vocabularies.registry import get_vocabulary_registry
    from src.dossier.catalog import load_recipes
    from src.dossier.distinctions import render_distinctions
    op = get_operationalization_registry().get("impact_scan"); assert [d.key for d in op.process.dimensions] == ["impact", "dependency", "retest"]
    assert get_vocabulary_registry().values_for("impact_scan", "run") == ["hunch_test", "reread", "frame", "distinction_round"]
    rec = {r["key"]: r for r in load_recipes()}["impact_scan"]; assert rec["context"] == ["distinction_settle", "distinction_draft", "encounter_draft"]
    out = ("[P1.F1] Part 6 complicates: the state's logic must be stated as imperatives, not a bare parity claim — dim: impact — part: 6 — relation: complicates — from: S1.F1 — anchor: \"they have a logic\" — doc: argument — confidence: high\n"
           "[P2.F1] Part 8 rests on part 6: the competing state now needs the imperatives named — dim: dependency — part: 8 — on: P1.F1 — how: premise — relation: moves — anchor: \"not captured but competing\" — doc: argument — confidence: medium\n"
           "[P3.F1] The hunch on Arrighi's territorial logic must be tested again on the new formulation — dim: retest — test: Arrighi's territorial logic generated by the system — run: hunch_test — because: it presupposed the parity claim — anchor: \"generated by the system\" — doc: hunches — confidence: medium")
    job = {"id": "d-imp", "analysis": {"4.1": {"engine_key": "impact_scan", "final_output": out, "final_wall": {"failed_ids": []}}}}
    d = render_distinctions(job)
    assert d["impact"]["touched"][0]["part"] == "6" and d["impact"]["touched"][0]["relation"] == "complicates"
    assert d["impact"]["dependencies"][0]["how"] == "premise" and d["impact"]["retests"][0]["run"] == "hunch_test" and d["vocabulary_drift"] == []
