"""Rebuild the two proposed definitions and the memo's verbatim method appendix. No production imports."""
from pathlib import Path
import yaml

HERE = Path(__file__).resolve().parent
KEY = 'citation_cohort_synthesis'
NAME = 'Engagement with a school across its members'
QUESTION = 'How does this author use, contest and selectively read the members of this cohort across the supplied work?'
PROBLEM = """A school is neither a single author nor the sum of its citation counts. Reconstruct A's pattern of reliance, authority, evidence, foil and dialogue across the approved members, the imbalance between frequency and argumentative consequence, and the dated changes that the pair ledgers support. Preserve the cohort's non-engaged residue and contested membership. Judge the reach and fidelity of A's reading only through the supplied audits. Distinguish a school named collectively from an engagement with a named person. The result is a scholarly reading with auditable tables, bounded by the work actually held and checked."""
LAW = """Do: Treat the pair ledgers as the evidence layer and pair tables and memos as navigation. Every substantive finding cites an immutable pair-row reference (<A_uid>__<P_uid>::<engine_key>::<row_id>) AND copies a verbatim anchor carried by that very row, with its pair document key and original source key/locus. Copy the scholar's words without correction or fresh quotation from memory. When the inherited anchor is insufficient, narrow the claim or request a new pair analysis; never silently re-anchor in this engine. For a cross-member claim supply separate anchor/row/doc groups for every member and every qualification needed, at least two distinct engaged member keys. Two engines, texts or memo restatements of one pair do not make two members. Rejected, unresolved-anchor and superseded rows cannot support prose or a table cell. Check nested attribution, coauthorship, modality, edition, dates and counterevidence in the inherited context; code checks shape and provenance, the model judges what the passages warrant. A restatement links its canonical row; never file or count it twice. The plan orders questions; it is not evidence. Cohort metadata citations are allowed only for membership, recorded counts, coverage and not-engaged reports, with an exact cohort-row anchor and explicit metadata basis. A missing analysis or unknown count is not zero engagement."""
DIMS = [
 ('member_uses','C1','document',True,'Each member’s argumentative work',[
  'For each engaged member, what proposition does A take over, use as authority or evidence, contest as a foil, or develop in dialogue?',
  'Which exact pair rows establish the move and stance, and which inherited qualification prevents a global label for this member?'],
  'Read each supplied pair’s engagement-map ledger first. Join move, stance, text and cited work by citation-event ID, not adjacency or matching theme. Retain adopted framework, authority, evidence, foil, dialogue, genealogy, illustration, courtesy and self-positioning as distinct moves, and adopts, builds_on, qualifies, disputes and mentions as proposition-specific stances. Use an optional reception row only as a labelled comparison, never as evidence A read that reader. On the cohort and plan return outside scope.',
  'pair: <pair key> — member: <P_uid> — event-ids: <canonical events> — move: <move> — stance: <stance> — proposition: <bounded proposition> — limit: <qualification>'),
 ('cohort_residue','C2','document',True,'Membership, counts and the members not engaged',[
  'Which approved members are engaged, not engaged, or unresolved according to the checked citation ledger, and why was each included?',
  'What exact corpus, date range, alias resolution and counting unit make a recorded zero meaningful?'],
  'Read only role: cohort for this dimension. Emit one not engaged row for every member in not_engaged_residue, quoting its cohort row; give the membership reason, ledger zero, search scope and limit, never a reading of that member. Emit unresolved rather than not engaged for incomplete identity resolution or unchecked counts. An engaged member lacking a required engagement ledger is a refusal before execution, not a negative finding. An empty residue is valid only when explicitly supplied and reconciled to the complete approved table. Count canonical citation events per member/text/year, keeping mention, bibliographic and collective-school events separate. Explain silence as a bounded observation. Any suggestion about its intellectual significance must be explicitly hypothetical and linked to a documented membership reason; never infer intent or ignorance.',
  'basis: cohort_metadata — cohort-row: <row_id> — member: <P_uid> — engaged: yes|no|unknown — report: <not engaged in checked corpus|engaged|unresolved> — membership-reason: <supplied reason> — count: <integer or unknown> — checked-scope: <coverage and date range> — limit: <what zero does not establish>'),
 ('cross_member_reliance','C3','corpus',True,'Reliance and opposition across members',[
  'Whose framework does A build on, whose authority or evidence does A invoke, and whom does A make a foil or dialogue partner?',
  'Does the contrast concern comparable propositions and texts, or different parts of the school; what would weaken the proposed ordering?'],
  'Compare at least two engaged members through their engagement rows on named propositions. Give an argued partial ordering of reliance with ties and incomparability, not a score computed from frequency. Distinguish borrowing a framework from citing an authority and distinguish an interlocutor from a foil. Preserve indirect engagement A → P → Q without turning it into a direct A → Q citation. Keep a collective-school address separate from personal pairs; its supporting rows cannot be allocated to a member by inference.',
  'members: <P_uid; Q_uid> — relation: <bounded ordering or contrast> — basis: <propositions and roles> — counterevidence: <row references or explicit limit>'),
 ('engagement_asymmetries','C4','corpus',True,'Frequency, concentration and consequence',[
  'Which member recurs frequently around one idea, and which appears rarely at a consequential turn in A’s argument?',
  'Do event counts and inspected readings warrant that asymmetry, and what proportion of the ledger remains unread?'],
  'Pair authoritative cohort event counts with engagement-map rows that show what the citations do. Frequency alone cannot establish influence, narrowness, neglect or a turning point. For “only one idea” require inspected coverage of all relevant canonical events, report the denominator and include the strongest exception; otherwise say “in the inspected passages.” For a turning point require an inherited reading of the argument’s change, not merely a single citation or a new publication year. If one side lacks that warrant, retain the numerical asymmetry and mark consequence unsettled.',
  'members: <P_uid; Q_uid> — event-counts: <counts and cohort-row refs> — inspected: <canonical events/eligible> — asymmetry: <bounded finding> — exception: <row or limit>'),
 ('school_periodization','C5','corpus',True,'A’s changing engagement with the school',[
  'What persists or changes in A’s treatment of the cohort across dated texts, and which members carry each period?',
  'Is an apparent shift a change in A’s position, a change of interlocutor, or a change in the supplied coverage?'],
  'Align dated propositions across at least two engaged members and at least two dated A texts before making a school-level period claim. For a before/after trajectory of a member require that member on both sides; a replacement of members is a compositional shift, not a conversion of either. Supply every endpoint row and qualifying span. Preserve coauthorship and unknown dates; same-year texts have no order unless explicit. Use periods as provisional model judgments, never bins generated by code or a career story supplied by the plan. When only one pair supports a trajectory keep it under member_uses as a reported pair trajectory and say school periodization is unresolved.',
  'members: <P_uid; Q_uid; ...> — texts-years: <dated endpoints> — relation: continuity|change|composition_shift|unordered — period: <bounded proposed period> — alternative: <coverage or interlocutor explanation>'),
 ('school_fidelity','C6','corpus',True,'The reach and fidelity of A’s reading',[
  'Across audited members, on what propositions is A’s reading accurate, fair, selective, stretched, misattributed or unverifiable?',
  'Do those local verdicts support a characterization of A’s reading of the school, and which missing works or contrary verdicts constrain it?'],
  'Read only final citable fidelity-audit verdicts, preserving their reasons, A-side and P-side anchors, editions, retrieval how and canonical citation IDs. Show every verdict by member without majority voting or averaging. Count each assessed citation once and distinguish not run, unverifiable and rejected evidence. A school-level characterization requires assessed verdicts for at least two members and explicit denominators; with one audit provide only its member-level entry and state insufficient school coverage. An unverifiable row can report a missing witness but cannot support a fidelity judgment. No supplied contrary primary witness means no new stretched or misattributed verdict. This engine never re-audits a text from memory.',
  'members: <audited P_uid; Q_uid> — audit-rows: <immutable refs> — verdict-pattern: <qualified pattern> — assessed-eligible: <per member> — missing: <works, editions, not-run audits>'),
 ('reception_alignment','C7','corpus',False,'Optional reception comparisons across members',[
  'Where the reception lens ran, how does A’s position align with or oppose held readers on the plan’s themes?',
  'Which apparent interlocutors are reference points only, and which engagements or silences have ledger evidence?'],
  'Use supplied reception-map rows for at least two members; otherwise report the one-pair comparison under member_uses or state lens not run. Keep plan_spine versus reader_addition, reader identity, reference-point role and excerpt scope. Analytical consonance is not demonstrated citation or influence. “Never engages” needs A-to-reader citation-ledger zeros with checked scope, not absence from the reception sample. Do not expand the cohort from reception readers or import their words as A’s.',
  'members: <P_uid; Q_uid> — themes: <theme and origin> — relation: <consonance|explicit opposition|no demonstrated engagement> — role: <reader|reference_point> — limit: <coverage>'),
]
SINGLE = ' — pair-row: <immutable pair-row ref> — anchor: "<verbatim anchor carried by that row>" — doc: <pair::<pair key>> — source-doc: <original key> — locus: <inherited printed/PDF page or registry section> — confidence: high|medium|low'
MULTI = SINGLE + ' — pair-row-b: <different member’s immutable row ref> — anchor-b: "<its carried verbatim anchor>" — doc-b: <different pair document> — source-doc-b: <original key> — locus-b: <inherited locus>; repeat labelled groups for all further supporting rows and qualifications'
META = ' — anchor: "<verbatim cohort row anchor>" — doc: context:cohort — confidence: high|medium|low'
TABLES = {
 'member_text_year_counts': 'member UID/name | membership reason [cohort-row] | engaged yes/no/unknown | A text key/title | year or unknown | canonical citation events | mentions | bibliography-only | inspected events/eligible | works cited | cohort-row refs. One row per member × A text × year, including explicit scoped zeros. A separate member-total row uses unique events, never sums duplicated renditions; collective-school events have their own identity.',
 'member_move_stance': 'member | A text/year | canonical event(s) | proposition | move | stance | inherited qualification | final cohort finding IDs | immutable pair-row refs | verbatim carried anchors | original doc keys/loci. Give separate cells/rows for distinct propositions; all substantive cells have complete evidence.',
 'fidelity_by_member': 'member | citation-event/audit-pair ID | A attribution | P position | verdict | reason | how (page/section/search when retrieved) | edition/locus | audited/eligible counts | final cohort finding IDs | immutable fidelity-row refs | A and P carried anchors. Preserve not_run, unverifiable and rejected counts outside the citable verdict totals; no averaged school score.',
 'not_engaged_members': 'member | role/reason for membership | engaged: no; not engaged in checked corpus | explicit ledger zero | checked texts/years and alias-resolution scope | cohort-row ID and verbatim metadata anchor | limits/possible significance (hypothesis only). Include every residue member once. With a verified empty residue say “none in the approved checked cohort”; unknowns get a separate unresolved list.',
 'cohort_periods': 'proposed period | members and dated A texts | continuity/change/composition shift | alternative/exception | final cohort finding IDs | all immutable endpoint refs and their carried anchors. If unsupported, one unresolved entry stating why; never fill periods from biography.'
}
PARTIAL = """The partiality paragraph must enumerate the approved cohort and disputed/excluded membership boundaries; A's held, inspected and missing texts and dates, coauthored coverage and ledger/alias/search completeness; each member's cited, held, fetched and still-wanted works and edition/translation or section/page ambiguities; engaged pairs supplied versus awaiting analysis; canonical events eligible/inspected/assessed, rejected rows and failed anchors; which fidelity and reception lenses ran or did not run and their checked denominators; collective-school mentions not allocated to people; unknown years; synthetic fixture content (if any, output is never release evidence); and the precise scope of silence and any periodization. Distinguish no evidence supplied, unresolved evidence and an explicit checked zero. Say what a fetched work or missing pair could change and which input revision would trigger a re-run. Preserve links to existing pair memos and canonical rows: a restatement is linked, never filed twice; the reader keeps the scholar's words."""
BRIEF = """Do: Follow the approved plan's section order while answering only questions supported by this packet. Lead with an argued cross-member reading, then the asymmetries, qualified periodization, audited fairness and scoped silence. Cite final cohort IDs in every substantive sentence and positive table cell; those IDs resolve to immutable pair rows AND their carried verbatim anchors. A row that repeats one pair's interpretation is labelled as such, not a cross-member finding. With fewer than two engaged pairs produce a clearly limited one-pair coverage report plus the full residue, never a simulated school synthesis. With no engaged pairs produce the metadata report only. Missing optional lenses reduce the claim, not the cohort.\n\nReconcile every final table cell after critic rulings and anchor walls. Do not leave a rejected, superseded, anchor-failed or dangling row in a table or prose; multiple supporting rows retain separate anchors. Coverage counts canonical citation events, not findings or memo restatements. Tables and memo copies are navigation, not independent corroboration. A refusal lists missing required artifacts before any interpretive output.\n\nRender the following tables with these columns:\n""" + '\n'.join(k + ': ' + v for k,v in TABLES.items()) + '\n\n' + PARTIAL + '\n\nClose with three to five existing pair passages worth opening and the concrete unresolved question. Use original pair memo links, exact source keys and inherited loci. Give no new quotation or chapter title from memory.'

def build():
 cap = dict(engine_key=KEY,engine_name=NAME,version=1,category='scholarly',kind='comparison',problematique=PROBLEM,researcher_question=QUESTION,intellectual_lineage={'primary':'source_criticism'},analytical_dimensions=[],apps=['critic'],function='genealogy',family='analytical')
 op = dict(engine_key=KEY,engine_name=NAME,stance_operationalizations=[],depth_sequences=[{'depth_key':d,'mode':m} for d,m in [('surface','oneshot'),('standard','oneshot_checked'),('deep','dvs')]]+[{'depth_key':'dvs','process':'dvs'}])
 dims=[]
 for key,prefix,scope,load,name,qs,card,fields in DIMS:
  cap['analytical_dimensions'].append(dict(key=key,description=name,probing_questions=qs))
  shape=f'[{prefix}.F<n>] <one bounded finding> — dim: {key} — '+fields+(META if key=='cohort_residue' else MULTI if scope=='corpus' else SINGLE)
  dims.append(dict(key=key,name=name,questions=qs,method_card='Do: '+card+'\n\n'+LAW,indicators=[],scope=scope,load_bearing=load,id_prefix=prefix,answer_shape=shape))
 op['process']=dict(key='dvs',description=QUESTION,framing=PROBLEM+'\n\n'+LAW+'\n\nRequired input: cohort-packet/v1, one author UID, approved cohort table with explicit not_engaged_residue (including [] when empty), role: plan, one document per engaged pair keyed pair::<A_uid>__<P_uid>, each with a final engagement-map ledger. Fidelity/reception ledgers optional. Refuse missing engagement ledgers, absent residue, inconsistent identities, count conflicts, and invalid or unverifiable provenance before calls. The transport/preflight adapter described in the memo is required; YAML alone does not enforce admission.',scoped_outcomes=True,routing=dict(cheap='openrouter/openai/gpt-5.6-luna',mid='openrouter/deepseek/deepseek-v4-pro',strong='openrouter/openai/gpt-5.6-sol'),dimensions=dims,steps=[dict(key='extract',kind='extract',parallel_over='dimension_x_document',model_tier='cheap',output='ledger',max_rows=20),dict(key='verify',kind='verify',consumes=['extract'],model_tier='mid',output='ledger',duties=['check_anchors_in_context','merge_duplicates','hunt_misses','name_must_keep',LAW,'Check every member endpoint, event-count denominator, dated trajectory and attribution chain. Preserve contrary rows and disputed membership. Distinguish not_run from unverifiable and zero from missing. Rulings apply to every final cell and prose citation; no rejected row survives.']),dict(key='synthesize',kind='synthesize',consumes=['verify'],model_tier='strong',output='prose_ledger',is_final=True,reader='a scholar of A with the pair ledgers and original cited passages open',tables=list(TABLES),brief=BRIEF)])
 for suffix,obj in [('capability',cap),('operationalization',op)]:
  (HERE/f'{KEY}.{suffix}.yaml').write_text('# Design candidate; no production registration before live validation.\n'+yaml.safe_dump(obj,sort_keys=False,allow_unicode=True,width=110))
 appendix=['## Questions, method cards and answer shapes in full','', 'Problematique: '+PROBLEM,'','Researcher question: '+QUESTION,'']
 for dim in dims:
  appendix.extend(['### '+dim['id_prefix']+' — '+dim['name'],'',f"`{dim['key']}`; scope `{dim['scope']}`; load-bearing `{dim['load_bearing']}`.",''])
  appendix.extend('- '+q for q in dim['questions'])
  appendix.extend(['',dim['method_card'],'','```text',dim['answer_shape'],'```',''])
 appendix.extend(['### Synthesis card and table specifications','',BRIEF,''])
 (HERE/'METHOD_APPENDIX.md').write_text('\n'.join(appendix))

if __name__=='__main__': build()
