"""Shared declarative adaptive-spec keys used by schema validation and runtime dispatch."""

from __future__ import annotations

SIGNAL_EXTRACTOR_KEY_RELATIONSHIP_SURFACE_SIGNALS_V1 = "relationship_surface_signals_v1"
SIGNAL_EXTRACTOR_KEY_CONDITIONS_SURFACE_SIGNALS_V1 = "conditions_surface_signals_v1"

BUILDER_TEMPLATE_KEY_RELATIONSHIP_PROFILE_DOSSIER = "relationship_profile_dossier"
BUILDER_TEMPLATE_KEY_RELATIONSHIP_COMPARISON_REVIEW = "relationship_comparison_review"
BUILDER_TEMPLATE_KEY_CONDITIONS_BALANCE_SHEET = "conditions_balance_sheet"
BUILDER_TEMPLATE_KEY_CONDITIONS_PATH_DEPENDENCY_MATRIX = "conditions_path_dependency_matrix"

ALLOWED_OPERATOR_KEYS = frozenset({"eq", "gte"})
ALLOWED_SIGNAL_EXTRACTOR_KEYS = frozenset(
    {
        SIGNAL_EXTRACTOR_KEY_RELATIONSHIP_SURFACE_SIGNALS_V1,
        SIGNAL_EXTRACTOR_KEY_CONDITIONS_SURFACE_SIGNALS_V1,
    }
)
ALLOWED_BUILDER_TEMPLATE_KEYS = frozenset(
    {
        BUILDER_TEMPLATE_KEY_RELATIONSHIP_PROFILE_DOSSIER,
        BUILDER_TEMPLATE_KEY_RELATIONSHIP_COMPARISON_REVIEW,
        BUILDER_TEMPLATE_KEY_CONDITIONS_BALANCE_SHEET,
        BUILDER_TEMPLATE_KEY_CONDITIONS_PATH_DEPENDENCY_MATRIX,
    }
)
