"""Register the estate's mirrored methods as engine definitions (2026-09-04).

Wirecut, de-llm and the Referee keep their doctrines in their own repos today;
the registry mirrors each named method as an EngineDefinition with
family / home_organ / runs_at / lineage_refs / sync="mirrored", so The Master
can show and, later, serve them. The Analyst's own process engines and the
designed imagination/governance engines are registered too.

Idempotent: re-running rewrites the same files. Existing analytical engine
definitions are never touched.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
import sys
sys.path.insert(0, str(ROOT))
DEFS = ROOT / "src" / "engines" / "definitions"
WF_DIR = ROOT / "src" / "workflows" / "definitions"

DESK = "https://the-analyst-desk.onrender.com"
WIRECUT = "https://veo2-waum.onrender.com"
DELLM = "https://dellmify.onrender.com/longform"
REFEREE = "https://gs-revamp-v2-sg.onrender.com/v2/ui"


def stage_context(name: str, plural: str, question: str) -> dict:
    """Minimal valid StageContext for a mirrored method (doctrine lives elsewhere)."""
    return {
        "extraction": {"analysis_type": name, "analysis_type_plural": plural, "core_question": question},
        "curation": {"item_type": name, "item_type_plural": plural},
        "concretization": {},
        "skip_concretization": True,
    }


def E(key, name, family, category, kind, organ, runs_at, description, question, focus, outputs, lineage, *, status="live", sync="mirrored", grounding=None, version=1):
    from src.story.demands import DEMANDS

    return dict(
        source_demands=DEMANDS.get(key, []),
        engine_key=key, engine_name=name, description=description, version=version,
        category=category, kind=kind, family=family, reasoning_domain=f"{family} · {organ}",
        researcher_question=question,
        stage_context=stage_context(name, name + "s", question),
        canonical_schema={},
        extraction_focus=focus, primary_output_modes=outputs, paradigm_keys=[],
        added_date="2026-09-04", source_file=lineage[0] if lineage else None,
        engine_profile=None, apps=[], function=None,
        home_organ=organ, runs_at=runs_at, lineage_refs=lineage, status=status, sync=sync,

    )


ENGINES = [
    # ───────────────────────── Wirecut (veo2) ─────────────────────────
    E("wirecut_spine", "Spine", "storytelling", "storytelling", "synthesis", "wirecut", WIRECUT,
      "Plans the film before the script. From the source, a preset and a length it declares an arc in named movements, a motif with its plant and payoff, a colour script, a musical arc, the hook strategy and the open loop the film will hold. Every later pass answers to the accepted spine.",
      "What is the one arc this material can carry, and where does it turn?",
      ["movements", "motif plant/payoff", "colour script", "musical arc", "hook", "open loop"], ["spine record"],
      ["veo2:engine/prompts/spine_doctrine.md", "veo2:engine/spine.py:827"]),
    E("wirecut_telling_desk", "Telling desk", "storytelling", "storytelling", "synthesis", "wirecut", WIRECUT,
      "Declares the thirteen telling dials over an accepted spine: the one question, whose film it is, the face on the stake, disclosure, the engine of the telling, the reveals, the verdict and the stance. The dials are the contract every downstream pass is held to.",
      "Whose story is this, what is at stake, and how is it disclosed?",
      ["question", "whose film", "face on the stake", "disclosure", "engine", "reveals", "verdict", "stance"], ["telling dials"],
      ["veo2:engine/prompts/telling_desk.md", "veo2:engine/telling.py:362", "veo2:communications/STORYTELLING_STUDY_2026-09-02/TELLING_PARAMETERS.md"]),
    E("wirecut_narrative_approaches", "Narrative approaches", "storytelling", "planning", "comparison", "wirecut", WIRECUT,
      "A closed catalogue of twelve film structures (helicopter view, one scene first, the case, the portrait, the timeline, the verdict, open question, the numbers, the correction, the object, the hindsight, the choice), each with a length window and an ending contract, plus the approach-suggest pass that ranks them against a source.",
      "Which structure fits this material, and what ending does it commit to?",
      ["approach", "length window", "ending contract", "ranking rationale"], ["ranked slate"],
      ["veo2:engine/storyboard.py:266", "veo2:engine/prompts/narrative_doctrine.md", "veo2:engine/prompts/approach_suggest.md"]),
    E("wirecut_screenwriter", "Screenwriter", "storytelling", "storytelling", "synthesis", "wirecut", WIRECUT,
      "Script first: writes the whole narration as one continuous read, beat by beat, from source and spine, then cuts to length and takes a red pen to every line. Findings of meta-leak, register drift, tics and inconsistency are named, not silently fixed.",
      "What does the narrator say, in one read, and where does it run long or false?",
      ["beats", "narration", "cuts", "red-pen findings"], ["script"],
      ["veo2:engine/prompts/screenwriter_doctrine.md", "veo2:engine/screenwriter.py:846", "veo2:engine/prompts/script_cut.md", "veo2:engine/prompts/script_pass.md"]),
    E("wirecut_storyboard", "Storyboard", "rendering", "planning", "synthesis", "wirecut", WIRECUT,
      "Turns a locked script into a board: per clip a visual prompt, continuity notes, a provider recommendation, a verbatim source anchor and a text layer. The board is where words become pictures that can be grounded.",
      "What does each clip show, and which sentence of the source licenses it?",
      ["visual prompt", "continuity", "provider", "source anchor", "text layer"], ["board"],
      ["veo2:engine/prompts/storyboard_doctrine.md", "veo2:engine/storyboard.py:3769"]),
    E("wirecut_pacing_editor", "Pacing editor", "editing", "editing", "synthesis", "wirecut", WIRECUT,
      "Reads the settled plan for rhythm: seam intents between clips, breather verdicts, held-question pauses and narration trims. It edits the clock, not the meaning.",
      "Where does the film breathe, and where does it drag?",
      ["seam intents", "breathers", "trims"], ["pacing verdicts"],
      ["veo2:engine/prompts/pacing_pass.md", "veo2:engine/pacing.py:447"]),
    E("wirecut_prompt_bench", "Prompt bench", "editing", "visual", "synthesis", "wirecut", WIRECUT,
      "Reads every visual prompt on the board as a description a stranger would draw from, checks it against the telling and the source, and rewrites gestures and vagueness in place.",
      "Would a stranger draw the right picture from this prompt?",
      ["rewritten prompts", "reasons"], ["board revisions"],
      ["veo2:engine/prompts/prompt_bench.md", "veo2:engine/prompt_bench.py:331"]),
    E("wirecut_grounding_review", "Grounding review", "quality", "quality", "extraction", "wirecut", WIRECUT,
      "Clip by clip, verdicts of grounded or ungrounded against the source. Ungrounded clips go back to the board; the review reports, it never blocks.",
      "Which clips can the source actually vouch for?",
      ["per-clip verdicts", "evidence"], ["grounding ledger"],
      ["veo2:engine/prompts/grounding_review.md", "veo2:engine/storyboard.py:4132"]),
    E("wirecut_text_layer", "Text layer", "rendering", "visual", "synthesis", "wirecut", WIRECUT,
      "Per-clip typography: roles, templates, verbatim checks, re-fit against a contact sheet of real frames. The typography doctrine is applied as law, so titles never say what the picture cannot support.",
      "What text belongs on this frame, in which role, and is it verbatim?",
      ["typography spec", "roles", "verbatim checks"], ["text layer plan"],
      ["veo2:engine/prompts/text_layer_doctrine.md", "veo2:engine/prompts/typography_doctrine.md", "veo2:engine/textlayer.py:2057"]),
    E("wirecut_scratch_vo", "Scratch VO / table read", "quality", "audio", "synthesis", "wirecut", WIRECUT,
      "A free read of every beat is listened to before any footage is bought: per-line keep or revise, delivery and voice notes, duration declarations. Rehearsals never spend.",
      "Does the narration hold when heard aloud, and how long is each beat really?",
      ["listened verdicts", "durations", "delivery notes"], ["table-read record"],
      ["veo2:engine/prompts/scratch_review.md", "veo2:engine/scratch_vo.py:767"]),
    E("wirecut_casting", "Casting", "storytelling", "audio", "synthesis", "wirecut", WIRECUT,
      "Which voice speaks each clip and with what delivery direction, cast from the script and the telling dials; pronunciation lexicon suggested alongside.",
      "Who speaks this line, and how?",
      ["role→voice", "delivery direction", "pronunciations"], ["casting sheet"],
      ["veo2:engine/prompts/casting_doctrine.md", "veo2:engine/voices.py:227"]),
    E("wirecut_music_brief", "Music brief", "storytelling", "audio", "synthesis", "wirecut", WIRECUT,
      "A footage-grounded music plan: brief and sections written from the contact sheet and the measured layout, then realized through a music model and re-heard in the sound check.",
      "What should the score do at each turn of the film?",
      ["music brief", "sections"], ["music plan"],
      ["veo2:engine/prompts/music_doctrine.md", "veo2:engine/prompts/music_sections_doctrine.md", "veo2:engine/music.py:322"]),
    E("wirecut_dailies", "Dailies", "quality", "quality", "synthesis", "wirecut", WIRECUT,
      "The film editor's call over a contact sheet of real frames: per-clip, per-boundary and whole-reel verdicts with concrete edit edges. No substitute verdict, ever: what the editor did not see is not judged. Dispositions are executed by the iterate loop inside a spend cap.",
      "Seen as a reel, what works, what breaks at the seams, and what is re-filmed?",
      ["clip verdicts", "boundary verdicts", "reel verdict", "edit edges"], ["dailies report"],
      ["veo2:engine/prompts/dailies.md", "veo2:engine/dailies.py:1171", "veo2:engine/iterate.py:107"]),
    E("wirecut_screening", "Screening", "quality", "quality", "synthesis", "wirecut", WIRECUT,
      "The judge on the assembled broadcast: a punch list and a ship-ready gate from a frame strip or the video itself. No unattended publication at any tier; the work order turns open punch targets into concrete acts.",
      "Is this ready to ship, and if not, what exactly must change?",
      ["punch list", "ship_ready", "work order"], ["screening report"],
      ["veo2:engine/prompts/screening.md", "veo2:engine/screening.py:1151", "veo2:engine/workorder.py:188"]),
    E("wirecut_retrospective", "Retrospective", "governance", "quality", "synthesis", "wirecut", WIRECUT,
      "A post-mortem written over the film's whole recorded life: every pass, receipt, verdict and cost. Lessons are stated for the next film, which is how the doctrine grows.",
      "What did this film's record teach, and what should the next one do differently?",
      ["lessons", "costs", "verdict history"], ["retrospective"],
      ["veo2:engine/prompts/retrospective.md", "veo2:engine/retrospective.py:350"]),
    E("wirecut_adjudicator", "Adjudicator", "quality", "quality", "synthesis", "wirecut", WIRECUT,
      "Rules a collision between the operator's settings and the material mid-write (clip count, length, structure), with a stated reason, so the writer neither ignores the setting nor breaks the story to obey it.",
      "When the settings and the material disagree, who wins and why?",
      ["ruling", "reason"], ["adjudication"],
      ["veo2:engine/prompts/adjudicator_doctrine.md", "veo2:engine/adjudicate.py:112"]),
    E("wirecut_retention_doctrine", "Retention doctrine", "storytelling", "storytelling", "synthesis", "wirecut", WIRECUT,
      "The laws of keeping a viewer: the first three seconds are the video, open loops honestly, every beat changes state, holds are earned. Doctrine applied by the writing passes and never measured by code.",
      "What keeps a viewer for the next beat?",
      ["laws"], ["doctrine"],
      ["veo2:engine/prompts/retention_doctrine.md", "veo2:communications/STORYTELLING_STUDY_2026-09-02/SYNTHESIS.md"]),
    E("wirecut_editions", "Editions", "restructuring", "restructuring", "synthesis", "wirecut", WIRECUT,
      "Rebuilds any finished film in another language: script, voices, text layer and subtitles re-derived from the record, footage kept.",
      "What must change for this film to speak another language?",
      ["translated script", "recast voices", "text layer"], ["edition"],
      ["veo2:engine/editions.py:294"]),

    # ───────────────────────── de-llm ─────────────────────────
    E("dellm_whole_read", "Whole read", "restructuring", "restructuring", "extraction", "de-llm", DELLM,
      "Reads the entire document once and states its plain summary, the buried crux, the readers and their mode, the governing contract, the strands that run through it, the form's capacity and the genre. Everything downstream cites this read.",
      "What is this document really about, for whom, and what does its form allow?",
      ["summary", "crux", "readers", "contract", "strands", "genre"], ["read record"],
      ["de-llm:delm/longform/prompts.py:27", "de-llm:delm/longform/program.py:625"]),
    E("dellm_deep_read", "Deep read", "restructuring", "restructuring", "extraction", "de-llm", DELLM,
      "Declares what the document runs on: twelve deep-structure elements marked stated, implicit or absent, five tests, and the latent elements the material could carry but does not yet.",
      "What does this argument run on, and what is it missing?",
      ["elements", "tests", "latent elements"], ["deep-structure record"],
      ["de-llm:delm/longform/prompts.py:109", "de-llm:delm/deep_structure.py:35"]),
    E("dellm_card_deck", "Card deck", "restructuring", "restructuring", "extraction", "de-llm", DELLM,
      "One card per section in John McPhee's manner: its job, its point, its claims, its terms, its dependencies, and whether it is anchored or mobile. The deck is what architecture candidates are built from.",
      "What does each section do, and can it move?",
      ["job", "point", "claims", "terms", "dependencies", "anchored/mobile"], ["cards"],
      ["de-llm:delm/longform/prompts.py:163", "de-llm:delm/longform/program.py:784"], grounding="John McPhee, Draft No. 4"),
    E("dellm_style_sheet", "Style sheet", "editing", "editing", "extraction", "de-llm", DELLM,
      "Compiles the manuscript's own conventions into a style sheet, as a copyeditor would, so later rewrites keep faith with the author's spellings, terms and habits.",
      "What conventions does this manuscript already keep?",
      ["conventions"], ["style sheet"],
      ["de-llm:delm/longform/prompts.py:229"], grounding="Amy Einsohn, The Copyeditor's Handbook"),
    E("dellm_architecture_candidates", "Architecture candidates", "restructuring", "restructuring", "synthesis", "de-llm", DELLM,
      "Diagnoses the current architecture, picks strategy families from thirteen (five of them re-foundings), drafts three trial leads, and writes a full section-level skeleton per family with its stance, deep structure and change profile, then ranks them by reader gain under the author's declared ambition: tidy, rebuild or open.",
      "What other shapes could this document take, and which serves the reader most?",
      ["diagnosis", "trial leads", "candidate skeletons", "ranking"], ["architecture slate"],
      ["de-llm:delm/longform/prompts.py:338", "de-llm:delm/longform/prompts.py:448", "de-llm:delm/longform/prompts.py:560", "de-llm:delm/longform/program.py:1229"]),
    E("dellm_restructuring_memo", "Restructuring memo", "composition", "composition", "synthesis", "de-llm", DELLM,
      "The choice screen rendered as a document: a letter written by the model over a computed record, presenting the candidate architectures for the author to choose from (memo 1), the plan with its signed removals (memo 2), and what the article now runs on (closing memo).",
      "How should the author be shown the choice, and what did we change?",
      ["letter", "record", "choices"], ["memo (md, pdf)"],
      ["de-llm:delm/longform/memo.py:359", "de-llm:delm/longform/prompts.py:1054"]),
    E("dellm_realization_plan", "Realization plan", "restructuring", "restructuring", "synthesis", "de-llm", DELLM,
      "One directive per section for the chosen shape: retain, move only, reframe, rewrite, compress, rebuild, restructure, merge into, split, cut, to annex, to front, with depth, compression, sibling contracts, author queries and new units. Signed removals are never decided by a default; the author adopts or rejects each one.",
      "What happens to every section under the chosen architecture?",
      ["dispositions", "contracts", "queries", "new units"], ["plan"],
      ["de-llm:delm/longform/prompts.py:634", "de-llm:delm/longform/realize.py:41"]),
    E("dellm_rules_at_the_desk", "Rules at the desk", "editing", "editing", "synthesis", "de-llm", DELLM,
      "Before writing a section, the model picks at most five craft rules from the packs that fit that section and states why. The rules come from the packs, the selection is judgment.",
      "Which craft rules govern this section, and why these?",
      ["selected rules", "reasons"], ["desk rules"],
      ["de-llm:delm/longform/prompts.py:1192", "de-llm:delm/longform/realize.py:1079"]),
    E("dellm_strand_drafting", "Strand drafting", "storytelling", "storytelling", "synthesis", "de-llm", DELLM,
      "A strand that recurs in three or more sections is written first as one piece, then distributed and checked for continuity, so the through-line survives the section-by-section rewrite.",
      "What runs through the whole, and does it still read as one thing?",
      ["strand draft", "continuity check"], ["strand ledger"],
      ["de-llm:delm/longform/prompts.py:1215", "de-llm:delm/longform/realize.py:1162"]),
    E("dellm_section_rewrite", "Section rewrite", "restructuring", "restructuring", "synthesis", "de-llm", DELLM,
      "Writes one section against its directive, the live seam with its neighbours, the thread ledger and the narrative stance, in the new reading order; new units (lead, verdict page, bridges, executive summary) follow in a frames pass, then heads are re-derived.",
      "What does this section say now, in its new place?",
      ["section text", "seam", "threads"], ["section"],
      ["de-llm:delm/longform/prompts.py:830", "de-llm:delm/longform/prompts.py:924", "de-llm:delm/longform/prompts.py:973"]),
    E("dellm_narrative_stance", "Narrative stance", "storytelling", "storytelling", "synthesis", "de-llm", DELLM,
      "Sixteen dimensions of how an argument is told (steering, disclosure, address, density and the rest) plus the form–content relation, with genre defaults and positions the author may hold. Enact-never-announce is a stance value, not a universal rule.",
      "How is this argument told, and how should it be?",
      ["dimensions", "genre defaults", "held positions"], ["stance record"],
      ["de-llm:delm/longform/stance.py:35", "de-llm:communications/NARRATIVE_STANCE_DIMENSIONS_2026-09-03.md"]),
    E("dellm_coherence_audit", "Coherence audit", "quality", "quality", "extraction", "de-llm", DELLM,
      "Whole-document findings across the audit categories, plus a strand audit (one strand read consecutively) and a reanchor sweep of every changed seam. Findings drive bounded per-section repairs and a re-audit until clean.",
      "Where does the regenerated document fail to cohere?",
      ["findings", "categories", "repairs"], ["audit"],
      ["de-llm:delm/longform/audit.py:71", "de-llm:delm/longform/audit.py:185", "de-llm:delm/longform/audit.py:1292"]),
    E("dellm_skeleton_reconstruction", "Skeleton reconstruction", "quality", "quality", "comparison", "de-llm", DELLM,
      "Cold re-derivation of the document's skeleton from its navigational surface only (heads, leads, closes), compared against the intended architecture. If a reader cannot recover the shape, the shape is not there.",
      "Can the shape be recovered from the surface alone?",
      ["reconstructed skeleton", "diff"], ["skeleton compare"],
      ["de-llm:delm/longform/audit.py:142", "de-llm:delm/longform/audit.py:165"]),
    E("dellm_drift_adjudication", "Drift adjudication", "quality", "quality", "comparison", "de-llm", DELLM,
      "Per section, semantic drift against the source: invented fact, strengthened claim, dropped qualification, moved emphasis. Screens are signals; the adjudicator decides.",
      "Did the rewrite change what the source claims?",
      ["drift findings", "severity"], ["drift ledger"],
      ["de-llm:delm/longform/audit.py:223", "de-llm:delm/longform/audit.py:1001"]),
    E("dellm_independent_reader", "Independent reader", "quality", "quality", "synthesis", "de-llm", DELLM,
      "A plan-blind cold read on a different model than the writer: self-reference, scaffolding, repetition, seams, typos, stance. It knows nothing of the plan, which is the point.",
      "What does a stranger notice on first reading?",
      ["reader findings"], ["reader report"],
      ["de-llm:delm/longform/prompts.py:1113", "de-llm:delm/longform/audit.py:677"]),
    E("dellm_stance_placement", "Stance placement", "quality", "quality", "comparison", "de-llm", DELLM,
      "Majority-of-N readings place the delivered text on each stance dimension, compared with the stance the author held; deep-structure checks (dichotomy early, mechanism once, metaphor before use) ride alongside as advisory.",
      "Where does the delivered text actually sit on each dimension?",
      ["placements", "advisories"], ["placement record"],
      ["de-llm:delm/longform/prompts.py:1170", "de-llm:delm/longform/audit.py:647", "de-llm:delm/longform/audit.py:317"]),
    E("dellm_resolution", "Resolution", "editing", "editing", "synthesis", "de-llm", DELLM,
      "Author-directed handling of each finding: keep the rewrite, restore the source, replace, or go further. Nothing is applied that the author has not adopted.",
      "For each finding, what does the author want?",
      ["decisions"], ["resolved document"],
      ["de-llm:delm/longform/prompts.py:1034", "de-llm:delm/longform/resolve.py:37"]),
    E("dellm_rule_packs", "Craft rule packs", "governance", "editing", "primitive", "de-llm", DELLM,
      "385 source-grounded craft rules in six versioned packs (craft, paragraph, document, operations, structural lenses, narrative foundations), each with principle, rationale, scopes, edit moves, signals, procedure, avoid-when, preserve, conflicts, sources and before/after examples. Projected into prompts mechanically; selected by judgment.",
      "What do the books say a good editor does here?",
      ["rules", "sources", "examples"], ["rule catalogue"],
      ["de-llm:delm/rulepacks.py:19", "de-llm:data/rule_packs/narrative-foundations.json", "de-llm:data/rule_lineage/"]),
    E("dellm_auto_humanize", "Auto-humanize loop", "editing", "editing", "synthesis", "de-llm", DELLM,
      "A detector-driven rewrite loop with a semantic-fidelity screen, an editorial AND gate, a binding verifier and a terminal whole-draft adjudication: the text is made to read as written, without changing what it says.",
      "Can this be made to read as written while meaning the same?",
      ["rewrites", "fidelity screen", "verdicts"], ["humanized draft"],
      ["de-llm:delm/auto_humanize.py:766"]),

    # ───────────────────────── The Referee / gs_revamp ─────────────────────────
    E("referee_slicing_lenses", "Slicing lenses", "search", "search", "synthesis", "gs-revamp", REFEREE,
      "Five ways to cut an objective into lanes: temporal, structural, conceptual, relational, epistemic. The planner picks a lens and emits lanes, term pools, cards, a budget advisory and an expected slate profile; the operator approves or requests changes.",
      "How should this objective be sliced into searchable lanes?",
      ["lens", "lanes", "budget advisory", "expected slate"], ["plan"],
      ["gs_revamp:src/gs_revamp/agent/prompts.py:405", "gs_revamp:src/gs_revamp/agent/tools.py:2017"]),
    E("referee_lane_card_program", "Lane and card program", "search", "search", "primitive", "gs-revamp", REFEREE,
      "A lane is the allocation unit: intent, phase, typed term pool, orientation categories, example queries, a query budget and a vocabulary confidence. A card is a small experiment inside a lane with its own objective, rationale, budget, stop conditions and status.",
      "What is each lane for, and what small experiments does it run?",
      ["lanes", "cards", "budgets", "stop conditions"], ["program"],
      ["gs_revamp:src/gs_revamp/agent/state.py:907", "gs_revamp:src/gs_revamp/agent/state.py:928"]),
    E("referee_term_harvest", "Term harvest", "search", "search", "extraction", "gs-revamp", REFEREE,
      "Typed vocabulary by category, lane and status. Terms are harvested at every evaluation and must be deployed or waived; lanes the planner marks low-confidence get a pre-run web vocabulary harvest from an online model.",
      "What words does this field use that we did not seed?",
      ["harvested terms", "categories", "deployment"], ["term pools"],
      ["gs_revamp:src/gs_revamp/agent/prompts.py:2637", "gs_revamp:src/gs_revamp/agent/webvocab.py"]),
    E("referee_adjustment_repertoire", "Adjustment repertoire", "search", "search", "primitive", "gs-revamp", REFEREE,
      "The named moves the agent must declare after each evaluation: BROADEN, TIGHTEN, PRUNE, RE-WINDOW, GO DEEPER, ANCHOR, WALK CITATIONS, AUTHOR CORPUS, REWRITE LANE, ABANDON. Vary the shape of the query, not only its vocabulary.",
      "Given what came back, what is the next move?",
      ["next_move", "query deltas"], ["move"],
      ["gs_revamp:src/gs_revamp/agent/prompts.py:88", "gs_revamp:src/gs_revamp/agent/tools.py:1132"]),
    E("referee_query_anatomy", "Query anatomy", "search", "search", "primitive", "gs-revamp", REFEREE,
      "Every search call declares its effectors as {kind, fragment, why} across sixteen kinds (quoted phrase, or-group, intitle, author anchor, source filter, year window, cited-by walk, language pivot, zero rescue, existence probe…) with typed term provenance. Anatomy-less searches are rejected and not budgeted.",
      "What exactly is this query doing, and why each part?",
      ["effectors", "provenance"], ["query record"],
      ["gs_revamp:src/gs_revamp/agent/prompts.py:121", "gs_revamp:communications/QUERY-CRAFT-DOCTRINE-MEMO.md"]),
    E("referee_batch_judging", "Batch judging", "quality", "search", "comparison", "gs-revamp", REFEREE,
      "A cheap seat disposes every returned paper as direct, adjacent, off-lane or garbage, with discovery value and seed suitability; batch verdict bands (more than two thirds, one third to two thirds, under one third) drive CONTINUE, FOCUS or ABANDON. Novelty signals (seen before, times seen, trend) read saturation.",
      "How much of what came back is what we wanted, and is the well running dry?",
      ["dispositions", "discovery value", "novelty"], ["batch assessment"],
      ["gs_revamp:src/gs_revamp/agent/tools.py:2948", "gs_revamp:src/gs_revamp/agent/prompts.py:270"]),
    E("referee_query_eval", "Query evaluation", "search", "search", "synthesis", "gs-revamp", REFEREE,
      "After each query: relevance, novelty, the next move, query deltas, harvested terms, the card verdict, escalation and seed status. An independent eval-substance verifier can bounce a thin evaluation and force a scoped redo.",
      "What did this query teach, and what follows from it?",
      ["relevance", "novelty", "next move", "harvested terms"], ["eval record"],
      ["gs_revamp:src/gs_revamp/agent/tools.py:2657", "gs_revamp:src/gs_revamp/agent/prompts.py:1148"]),
    E("referee_reverse_citation_test", "Reverse citation test", "search", "search", "synthesis", "gs-revamp", REFEREE,
      "Seeds are admitted only if walking their citations would plausibly reach the objective; seed status moves through continue, go deeper, switch, exhausted, abandoned. The citation phase spends a reserved budget on methodical cited-by walks.",
      "Whose citations are worth walking, and when is a seed spent?",
      ["seeds", "status", "walks"], ["citation program"],
      ["gs_revamp:src/gs_revamp/agent/prompts.py:63"]),
    E("referee_two_pool_budget", "Two-pool budget", "governance", "search", "primitive", "gs-revamp", REFEREE,
      "The query budget is sovereign; cost, minutes and model calls are backstops sized above it. Lanes allocate from a program pool; the citation reserve is the one hard wall, resized to the declared walk program. Budget exhaustion is stamped mechanically; early finish must be earned.",
      "How much may this run spend, and where is the wall?",
      ["pools", "allocations", "backstops"], ["budget"],
      ["gs_revamp:src/gs_revamp/agent/budgeting.py:178", "gs_revamp:src/gs_revamp/agent/prompts.py:18", "gs_revamp:CLAUDE.md"]),
    E("referee_truth_ledger", "Truth ledger and program frontier", "governance", "governance", "primitive", "gs-revamp", REFEREE,
      "The actual transport per query, the actual model per call, simulated-versus-live provenance; and the program frontier of named gaps and prepared units with terminal, evidence-linked dispositions. Nothing claims to have happened without a receipt.",
      "What actually happened in this run, and what is still open?",
      ["transport", "models", "gaps", "dispositions"], ["ledger"],
      ["gs_revamp:src/gs_revamp/agent/state.py:1523", "gs_revamp:src/gs_revamp/agent/tools.py:3136"]),
    E("referee_finish_gate", "Finish gate and tail director", "quality", "search", "synthesis", "gs-revamp", REFEREE,
      "Finishing requires a completion basis, an expansion review, recurrence and composition dispositions, and an independent verifier that can refuse. A stalled executor is answered by the tail director, whose schema can direct but never grant a stop.",
      "Has this run earned its finish?",
      ["completion basis", "verifier verdict", "directives"], ["finish record"],
      ["gs_revamp:src/gs_revamp/agent/tools.py:3200", "gs_revamp:src/gs_revamp/agent/tail_director.py", "gs_revamp:src/gs_revamp/agent/loop.py:2077"]),
    E("referee_critique_ledger", "Critique ledger", "governance", "governance", "primitive", "gs-revamp", REFEREE,
      "Cross-run findings, with approved ones promoted to versioned doctrine addenda; sibling ledgers track code-targeted improvements and author-identification failures. This is how the search doctrine learns.",
      "What did the last runs teach the doctrine?",
      ["findings", "addenda"], ["ledger"],
      ["gs_revamp:src/gs_revamp/agent/critique_ledger.py", "gs_revamp:src/gs_revamp/agent/improvement_ledger.py"]),
    E("reporter_domain_search_loop", "Domain search loop", "search", "search", "synthesis", "the-reporter", None,
      "The Reporter's core, dictated 2026-09-03: a dynamic, LLM-driven, context-sensitive search inside chosen domains (site: FT, Economist, Bloomberg, NYT, WSJ). Discover the terms that represent the topic, try combinations, evaluate the results, harvest new terms from them, refine, inside a budget with a truth ledger. Lineage: the Referee's lanes and moves and web-saver's adaptive exhaustion.",
      "What has the press said about this, and what words does it use to say it?",
      ["terms", "queries", "judged results", "harvested terms"], ["search program"],
      ["the-reporter:BOOTSTRAP_PROMPT.md", "the-reporter:communications/HUNCHES_AND_ARCHITECTURE.md", "web-saver:web-app/adaptive_exhaustion.py:188"], status="designed", sync="planned"),

    # ───────────────────────── The Analyst's process engines ─────────────────────────
    E("analyst_reconnaissance", "Reconnaissance", "composition", "composition", "extraction", "the-analyst", DESK,
      "Reads the corpus before anything is promised: what the documents are, who speaks in them, what they would let a reader understand and do, and how large the job is. The brief is written from this read, not from the file names.",
      "What is in this material, and what could be made from it?",
      ["documents", "speakers", "affordances", "size"], ["recon record"],
      ["the-analyst:src/dossier/runner.py", "the-analyst:src/dossier/reconnaissance.py"], sync="native"),
    E("analyst_brief", "Brief", "composition", "composition", "synthesis", "the-analyst", DESK,
      "Deliverable-first options: each says what the reader will understand and be able to do, with the engines demoted to a 'how' line and a cost. Three entry lanes: state an intent and get options; pick engines yourself; let the material decide. Nothing is spent before a choice.",
      "What could this become for this reader, and what would it cost?",
      ["options", "deliverables", "recommendation", "cost"], ["brief"],
      ["the-analyst:src/dossier/brief.py", "the-analyst:communications/DESIGN_brief_deliverables.md"], sync="native"),
    E("analyst_plan", "Plan", "composition", "composition", "synthesis", "the-analyst", DESK,
      "Turns the chosen option into an executable plan over the registry's executable engines: phases, chains, passes and stances, sized to depth and audience, with the rationale and the alternatives recorded.",
      "Which engines, in what order, at what depth?",
      ["phases", "chains", "engines", "rationale"], ["plan"],
      ["the-analyst:src/dossier/plan.py", "the-analyst:src/orchestrator/planner.py"], sync="native"),
    E("analyst_spine", "Spine", "composition", "composition", "synthesis", "the-analyst", DESK,
      "A composition read over the analysis: one claim per section, in order, with the exhibits each section commissions (tables, figures, plates) named before any is drawn. Text, tables and figures then co-evolve from this spine.",
      "What does each section claim, and what must it show?",
      ["claims", "sections", "commissioned exhibits"], ["spine"],
      ["the-analyst:src/dossier/spine.py", "the-analyst:communications/DESIGN_concretization_passes.md"], sync="native"),
    E("analyst_tables", "Anchored tables", "composition", "composition", "extraction", "the-analyst", DESK,
      "Tables whose every cell carries an anchor: the document and the verbatim quote it rests on. A wall rejects any row whose anchor cannot be found in the source.",
      "What does the evidence say, cell by cell, and where exactly?",
      ["rows", "anchors", "quotes"], ["tables"],
      ["the-analyst:src/dossier/tables.py"], sync="native"),
    E("analyst_figure_planner", "Figure planner", "rendering", "visual", "synthesis", "the-analyst", DESK,
      "Plans analytical diagrams, never illustrations: a FigureSpec chooses one of twelve primitives and a visual format, passes v1's format enforcement and global prohibitions, takes a style school, renders at 2K through the image fleet, is checked by Claude vision as a diagram, and is revised once.",
      "Which diagram makes this section's claim visible, and does the render obey the grammar?",
      ["primitive", "format", "style", "compliance"], ["figures"],
      ["the-analyst:src/dossier/figures.py", "the-analyst:src/display/enforcement.py", "the-analyst:src/images/adapter.py"], sync="native"),
    E("analyst_plate_planner", "Plate planner", "rendering", "visual", "synthesis", "the-analyst", DESK,
      "Report-as-diagram plates in v1's families (scorecard, framework map, flow map, power map, timeline of shifts, register, layer stack, argument tree): a PlateSpec per plate, v1's assembly order, 4K render, tiled vision check, leak scan. Refuses a register when the tables already exist; prefers diagrammatic families.",
      "Which whole-report diagrams should this dossier carry?",
      ["family", "spec", "compliance"], ["plates"],
      ["the-analyst:src/dossier/plates.py", "the-analyst:src/dossier/plate_store.py"], sync="native"),
    E("analyst_compose", "Compose", "composition", "composition", "synthesis", "the-analyst", DESK,
      "Writes the body with the exhibits already in hand, placing each table and figure at the pointer where the argument needs it, frames last, plates as an appendix. The prose knows what the pictures show.",
      "How does the argument read with its exhibits in place?",
      ["sections", "pointers", "frames"], ["dossier (html, md, pdf)"],
      ["the-analyst:src/dossier/compose.py", "the-analyst:src/dossier/templates/dossier.html.j2"], sync="native"),
    E("analyst_crosscheck", "Cross-check", "quality", "quality", "comparison", "the-analyst", DESK,
      "A judge reads the finished dossier with the rendered diagrams as vision input, and code clamps check anchors and pointers; findings go to a ledger and one round of safe realizations is applied at medium depth and above.",
      "Does the text say what the exhibits show, and do the anchors hold?",
      ["findings", "realizations"], ["findings ledger"],
      ["the-analyst:src/dossier/crosscheck.py"], sync="native"),
    E("analyst_receipts", "Receipts", "governance", "governance", "primitive", "the-analyst", DESK,
      "Every step's prompt hash, model, tokens, cost and output excerpt in the run-events ledger, streamed live and narrated in one line each by a small model, so the process is visible while it runs and auditable after.",
      "What did each step do, why, and what did it cost?",
      ["events", "costs", "narration"], ["receipts"],
      ["the-analyst:src/events/store.py", "the-analyst:src/events/narrator.py", "the-analyst:src/dossier/receipts.py"], sync="native"),


    # ───────────────────────── Multi-source storytelling (designed 2026-09-04) ─────────────────────────
    E("story_reconnaissance", "Story reconnaissance", "storytelling", "storytelling", "extraction", "wirecut", None,
      "Reads each source of a many-source film against the demands of the passes downstream: the questions it raises, the faces with a stake and what they chose, the turns (a value before and after, and what turned it), antagonisms, reveals, motif candidates, filmable places, objects and numbers, quotable lines, intensity, and what the source cannot support. Every element carries a verbatim anchor; the anchor wall drops the rest. One call per document; the result is a queryable ledger, not a summary.",
      "What in this document could a film be made of, and where exactly does it say so?",
      ["questions", "faces and stakes", "turns", "antagonisms", "reveals", "motif candidates", "filmables", "quotables", "anchors", "gaps"], ["story profile"],
      ["the-analyst:communications/DESIGN_multisource_storytelling.md", "the-analyst:src/dossier/reconnaissance.py", "veo2:communications/STORYTELLING_STUDY_2026-09-02/SYNTHESIS.md"], status="designed", sync="planned"),
    E("story_map", "Story map", "storytelling", "storytelling", "comparison", "wirecut", None,
      "Across the story profiles, not the documents: which faces, turns and objects recur; where sources contradict (antagonism the film can use) and where they corroborate; a timeline when the material is temporal; and candidate through-lines, each with its one question, face on the stake, the value that turns, the open loop, the sources that carry it and the sources that do not. A through-line is carried by at least two sources or is declared a single-source film with the rest as context. Emits a coverage matrix so a choice shows what it leaves out.",
      "What one current runs through these sources, and which of them are its tributaries?",
      ["recurrences", "contradictions", "timeline", "through-lines", "coverage matrix"], ["story map"],
      ["the-analyst:communications/DESIGN_multisource_storytelling.md", "gs_revamp:src/gs_revamp/agent/prompts.py:2637"], status="designed", sync="planned"),
    E("story_brief", "Story brief", "composition", "composition", "synthesis", "wirecut", None,
      "Deliverable-first options for a many-source film, in the law of the Analyst's brief: three options, each stating what the viewer will understand and feel, the length, the through-line, the ranked approach, the sources used and the cost. Nothing is rendered before the operator chooses.",
      "What film could this corpus become for this viewer, and what would each choice leave out?",
      ["options", "through-line", "approach", "sources used", "cost"], ["brief"],
      ["the-analyst:communications/DESIGN_multisource_storytelling.md", "the-analyst:src/dossier/brief.py", "the-analyst:communications/DESIGN_brief_deliverables.md"], status="designed", sync="planned"),

    # ───────────────────────── Imagination and governance (designed, from the July dictations) ─────────────────────────
    E("generativity_module", "Generativity module", "imagination", "imagination", "synthesis", "oaas", None,
      "Puts question clusters in tension and generates new questions not present in the corpus but extrapolatable from it, with Ernst Bloch's tendency, latency and not-yet as the instrument. Piloted 2026-07-15 over the megas; to be formalized as a registered engine.",
      "What does this material make thinkable that it does not yet say?",
      ["tensions", "candidate questions"], ["generative pilot"],
      ["oaas:communications/questions/QUESTIONS_GENERATIVE_PILOT.md", "oaas:communications/DICTATION_2026-07-15_process_engines_ACTIONS.md"], status="pilot", sync="planned"),
    E("residual_emergent_lens", "Residual / emergent lens", "imagination", "imagination", "synthesis", "oaas", None,
      "Raymond Williams as a service engine: analyze a situation by naming which of its elements are dominant, residual and emergent. Borderline analytical; imagination-based because it lets us see facets of reality through a creative naming, and may produce new frameworks rather than apply one.",
      "What in this situation is residual, what emergent, and what does naming them change?",
      ["dominant", "residual", "emergent"], ["lens reading"],
      ["oaas:communications/dictations/DICTATION_2026-07-15_process_engines_VERBATIM.md"], status="designed", sync="planned", grounding="Raymond Williams, Marxism and Literature"),
    E("meta_bridging_engine", "Meta-bridging engine", "imagination", "imagination", "comparison", "oaas", None,
      "A meta-engine over the repertoire: any problem is explainable from fifteen to twenty-five vantage points; find the best fit with existing theories, and treat the blanks as findings. Feeds a narrative of how conventional analysis would read the case and where it runs out.",
      "Which theories fit this problem, and which vantage points come up blank?",
      ["fits", "blanks", "bridges"], ["bridging map"],
      ["oaas:communications/dictations/DICTATION_2026-07-15_process_engines_VERBATIM.md"], status="designed", sync="planned"),
    E("moves_registry", "Moves registry", "governance", "governance", "primitive", "oaas", None,
      "A registry not of thinkers and frameworks but of the strategies by which thinkers are mobilized to make specific points (foil is not encounter), learned from the literature and the owner's own essays, so theorizing can call a move by name.",
      "How is this thinker usually mobilized, and how should we?",
      ["moves", "repertoires"], ["registry"],
      ["oaas:communications/dictations/DICTATION_2026-07-15_process_engines_VERBATIM.md"], status="designed", sync="planned"),
    E("feedback_engine", "Feedback engine", "governance", "governance", "synthesis", "oaas", None,
      "Centralized, cross-tool capture of the owner's verdicts with their reasons (feedback about feedback), building an explicit model that extrapolates one correction to unseen items across the estate. Design study briefed 2026-07-15; five feedback corpora already exist to learn from.",
      "Given this verdict and its reason, what would the verdict be on the next item?",
      ["verdicts", "reasons", "extrapolations"], ["owner model"],
      ["oaas:build_prompts/PROMPT_FEEDBACK_ENGINE_STUDY.md", "oaas:communications/DICTATION_2026-07-15_process_engines_ACTIONS.md"], status="designed", sync="planned"),
]


def W(key, name, category, organ, description, phases, output, target="", inputs=None):
    return dict(
        workflow_key=key, workflow_name=name, description=description, category=category, version=1,
        phases=[dict(phase_number=float(i + 1), phase_name=p[0], phase_description=p[1], engine_key=(p[2] if len(p) > 2 else None),
                     depends_on_phases=([float(i)] if i > 0 else [])) for i, p in enumerate(phases)],
        required_inputs=inputs or [], optional_inputs=[], output_description=output, linked_transformation_keys=[],
        source_project=organ, target_page=target,
    )


WORKFLOWS = [
    W("wirecut_broadcast", "Wirecut: text to broadcast", "process", "wirecut",
      "Runs in Wirecut (veo2), mirrored here. Multi-pass concretization from source to a narrated, subtitled film: each pass a named, priced, receipted call; the operator sovereign at every gate; coherence tiers off | look | iterate | studio decide how much of it runs.",
      [("Ingest and approach", "File or URL to text and language; the twelve narrative approaches ranked against the source.", "wirecut_narrative_approaches"),
       ("Spine", "The arc in movements, motif, colour script, musical arc, hook, open loop.", "wirecut_spine"),
       ("Telling desk", "Thirteen telling dials declared over the accepted spine.", "wirecut_telling_desk"),
       ("Script", "Whole narration as one read; cut to length; red pen; adjudication when settings and material collide.", "wirecut_screenwriter"),
       ("Board, pacing, prompt bench", "Per-clip prompts with source anchors; seams and breathers; every prompt read as a description and rewritten.", "wirecut_storyboard"),
       ("Grounding, text layer, casting, likeness", "Clip verdicts against the source; typography per clip; voices and delivery; named people declared.", "wirecut_grounding_review"),
       ("Table read", "A free read of every beat listened to before any footage is bought.", "wirecut_scratch_vo"),
       ("Render, arrival, dailies, iterate", "Footage rendered and repaired; each take judged on arrival; the editor's call over the contact sheet; dispositions executed inside a cap.", "wirecut_dailies"),
       ("Music, assemble, sound check, seam ear", "Music brief and sections; narrate, mix, subtitles, title card, stitch; the finished audio heard and adjusted.", "wirecut_music_brief"),
       ("Screening, work order, retrospective", "Punch list and ship-ready gate; open targets realized; post-mortem over the film's record.", "wirecut_screening")],
      "One MP4 with SRT and clips, plus receipts for every pass.", inputs=["source text or file", "preset", "length", "coherence tier"]),
    W("dellm_longform_program", "de-llm: long-form restructuring program", "process", "de-llm",
      "Runs in de-llm, mirrored here. Essay- and report-scale re-imagining: diagnose the architecture, imagine rivals, let the author choose from a memo, regenerate section by section, audit cold, repair, finalize. The loop is fractal; the memo is the choice screen rendered as a document.",
      [("Ingest", "Any file to canonical Markdown, block tree, heading tree, section partition."),
       ("Read and deep read", "Summary, crux, contract, strands, genre; the twelve elements the document runs on.", "dellm_whole_read"),
       ("Cards and style sheet", "One McPhee card per section; the manuscript's own conventions.", "dellm_card_deck"),
       ("Architecture", "Diagnosis, trial leads, three to five candidate skeletons, ranked under the author's ambition.", "dellm_architecture_candidates"),
       ("Memo 1 and choice", "The Restructuring Memo as a letter; the author chooses a shape (zero calls).", "dellm_restructuring_memo"),
       ("Plan, memo 2, approval", "One directive per section; signed removals adopted or rejected explicitly (zero calls).", "dellm_realization_plan"),
       ("Generate", "Desk rules chosen; strands drafted whole; sections written in the new order; frames; retitle.", "dellm_section_rewrite"),
       ("Assemble, screens, audit", "Document assembled; mechanical screens; coherence, skeleton, strand, drift, deep-structure, independent reader, stance placement.", "dellm_coherence_audit"),
       ("Repair", "Bounded per-section repairs, re-audit, loop until clean.", "dellm_resolution"),
       ("Finalize", "Final document and the closing memo: what the article now runs on.", "dellm_restructuring_memo")],
      "A restructured document (md, docx, pdf), the memos, the audit record, and per-finding resolutions.", inputs=["document", "ambition: tidy | rebuild | open"]),
    W("referee_search_loop", "The Referee: budgeted search loop", "process", "gs-revamp",
      "Runs in gs_revamp, mirrored here. From objective to ranked slate and corpus: a planner slices the objective into lanes and cards, the operator approves, and an executor searches adaptively inside a sovereign query budget, declaring a named move and harvesting terms after every evaluation, then walks citations and must earn its finish.",
      [("Budgets", "Query budget is law; cost, minutes and calls are backstops sized above it.", "referee_two_pool_budget"),
       ("Plan", "A slicing lens; lanes with term pools and cards; budget advisory; expected slate profile.", "referee_slicing_lenses"),
       ("Approval gate", "The operator approves or requests lane edits."),
       ("Vocabulary harvest", "Low-confidence lanes get an online vocabulary harvest before the run.", "referee_term_harvest"),
       ("Execution loop", "Search with declared anatomy; batch judging; evaluation with next move and harvested terms; slate and frontier maintenance.", "referee_query_eval"),
       ("Citation phase", "Seeds admitted by the reverse citation test; methodical cited-by walks on the reserve.", "referee_reverse_citation_test"),
       ("Finish gate", "Completion basis, expansion review, dispositions; the verifier can refuse; the tail director answers stalls.", "referee_finish_gate"),
       ("Post-run cascade", "Assessment, merge, final order, editorial, synthesis, critic, corpus critic, author enrichment, export.", "referee_truth_ledger")],
      "A ranked slate, a corpus, the truth ledger and the program frontier.", inputs=["objective", "query budget"]),
    W("reporter_news_brief", "The Reporter: research question to news brief", "process", "the-reporter",
      "Planned (bootstrap written 2026-09-03). Free recall first, then the dynamic domain search loop, entitled fetch from a logged-in desktop, a headed bundle to The Analyst, and a brief in the library, commissioned by a button in the Referee.",
      [("Recall", "The Reader's newsletters, the Syllabus corpus by decade, the Archivist's bodies."),
       ("Domain search loop", "Term discovery, combinations, evaluation, harvest, refinement inside site: domains with a budget.", "reporter_domain_search_loop"),
       ("Entitled fetch", "Full text through the desktop daemon ladder; teasers parked and named."),
       ("Store and catalogue", "Bodies and receipts stored; gaps recorded honestly."),
       ("Analyst handoff", "A headed bundle to The Analyst; a dossier with diagrams comes back.", "analyst_brief"),
       ("Brief library", "The brief stored with its receipts and linked back to the Referee query.")],
      "A news brief with sources, gaps, analysis and diagrams.", inputs=["objective", "papers", "date window", "sites", "budgets"]),
    W("wirecut_multisource_story", "Wirecut: many sources, one film (planned)", "process", "wirecut",
      "Designed 2026-09-04 (communications/DESIGN_multisource_storytelling.md). Before storytelling begins, every source is read against the demands of the passes downstream and mapped into candidate through-lines; the operator chooses from a deliverable-first brief; the spine then runs with sources as tributaries and the existing chain follows, each clip anchored to the specific source it draws on.",
      [("Ingest many", "Uploads, stacks bundles or exemplars resolved into a headed corpus (the Analyst's source resolver)."),
       ("Story reconnaissance", "One story profile per document, fields = the downstream passes' demands, every element anchored; the anchor wall drops the rest.", "story_reconnaissance"),
       ("Story map", "Recurrences, contradictions, timeline, candidate through-lines with tributaries, coverage matrix.", "story_map"),
       ("Approach slate", "The twelve structures ranked against the map; per approach, which sources carry it and what must be cut.", "wirecut_narrative_approaches"),
       ("Brief", "Three deliverable-first options; nothing rendered before the choice.", "story_brief"),
       ("Spine with tributaries", "Movements assigned to sources; motif from the recurring elements; each source's entry point declared.", "wirecut_spine"),
       ("The chain", "Telling desk to screening as today; grounding checks each clip against its own source; the screenwriter names the tributary of each beat; later passes harvest from the ledger before re-reading.", "wirecut_grounding_review")],
      "A film with receipts naming which source each clip draws on, plus the story map and brief in the library.", inputs=["sources (many)", "preset", "length", "coherence tier"]),
    W("analyst_figure_pipeline", "The Analyst: figure pipeline", "rendering", "the-analyst",
      "How one analytical diagram is made inside the dossier process: spec, primitive, format, enforcement, style, render, vision check, one revision. Diagrams, never illustrations.",
      [("Figure spec", "The spine's commissioned exhibit becomes a FigureSpec: claim, data, primitive candidates.", "analyst_figure_planner"),
       ("Primitive and format", "One of twelve primitives; a visual format from the catalogue."),
       ("Enforcement wall", "v1's format enforcement and global prohibitions; duplicate formats rejected."),
       ("Style school", "One of six styles applied as a directive."),
       ("Render", "2K through the image fleet (Gemini 3 Pro Image by default)."),
       ("Vision check", "Claude vision judges it as a diagram against the spec; one revision if it fails.", "analyst_crosscheck")],
      "A labelled analytical diagram with its spec and compliance record.", target="figures"),
    W("analyst_plate_pipeline", "The Analyst: plate pipeline", "rendering", "the-analyst",
      "How a report-as-diagram plate is made: family, spec, v1's assembly order, 4K render behind a gate, tiled vision check, leak scan, appendix.",
      [("Plan plates", "Families chosen from the dossier's spine and tables; registers refused when tables exist.", "analyst_plate_planner"),
       ("Plate spec", "Title, cells, currents, axes and legend written from the analysis, verbatim where anchored."),
       ("Assembly order", "v1's order: frame, spine, currents, branches, labels, legend."),
       ("Render 4K", "Behind a render gate (one at a time on the current plan)."),
       ("Tiled vision check and leak scan", "Each tile read for compliance and text leaks; one revision."),
       ("Appendix", "Plates appended to the dossier with their specs.", "analyst_compose")],
      "4K plates with compliance records, shown on the desk's plates page.", target="plates"),
    W("v1_image_pipeline", "Analyzer v1: per-image pipeline (frozen)", "rendering", "analyzer-v1",
      "The client's production pipeline for one image, frozen 2026-09-03: scene prose, declutter, style guide and format enforcement, 4K, Claude-vision compliance, storage. The Analyst's figure and plate pipelines descend from it.",
      [("Scene prose", "The engine's curated findings written as a scene."),
       ("Declutter", "The scene reduced to what the diagram must carry."),
       ("Style guide and format enforcement", "House style and the format's rules applied as prompt law."),
       ("Render 4K", "Gemini 3 Pro Image."),
       ("Compliance", "Claude vision checks the render against the enforcement."),
       ("Store", "R2 storage and the report assembled.")],
      "One 4K plate per engine run.", target="report"),
]


def main() -> None:
    for e in ENGINES:
        path = DEFS / f"{e['engine_key']}.json"
        if path.exists():
            try:
                prev = json.loads(path.read_text())
                if prev.get("doctrine_files"):
                    e = {**e, "doctrine_files": prev["doctrine_files"]}
            except Exception:  # noqa: BLE001
                pass
        path.write_text(json.dumps(e, indent=2, ensure_ascii=False) + "\n")
    for w in WORKFLOWS:
        (WF_DIR / f"{w["workflow_key"]}.json").write_text(json.dumps(w, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {len(ENGINES)} engine definitions and {len(WORKFLOWS)} workflows")


if __name__ == "__main__":
    main()
